import lib1 from './img/l1.webp';
import lib2 from './img/l2.jpg';
import lib3 from './img/l3.jpg';
import lib4 from './img/l4.jpeg';


const libraryData = [
  {
    id: 1,
    image: lib1,
    title: 'New Library',
    city: 'Lucknow',
    location: 'BKT Lucknow Sitapur Road near SR College',
    price: 50,
    latitude: 26.8467,
    longitude: 80.9462,
    totalseats: 32,
    openingTime: '08:00 a.m',
    closingTime: '11:00 p.m',
    
  },
  {
    id: 2,
    image: lib2,
    title: 'Central Library',
    city: 'Delhi',
    location: 'Connaught Place, New Delhi',
    price: 75,
    latitude: 28.633,
    longitude: 77.219,
    totalseats: 50,
    openingTime: '08:00 a.m',
    closingTime: '11:00 p.m',
  },
  {
    id: 3,
    image: lib3,
    title: 'City Library',
    city: 'Lucknow',
    location: 'Aliganj, Lucknow',
    price: 40,
    latitude: 26.885,
    longitude: 80.949,
    totalseats: 20,
    openingTime: '08:00 a.m',
    closingTime: '11:00 p.m',
  },
  {
    id: 4,
    image: lib4,
    title: 'Community Library',
    city: 'Delhi',
    location: 'Khan Market, New Delhi',
    price: 60,
    latitude: 28.600,
    longitude: 77.227,
    totalseats: 25,
    openingTime: '08:00 a.m',
    closingTime: '11:00 p.m',
  },
  {
    id: 5,
    image: lib3,
    title: 'Modern Library',
    city: 'Gorakhpur',
    location: 'Golghar, Gorakhpur',
    price: 55,
    latitude: 26.7606,
    longitude: 83.3732,
    totalseats: 15,
    openingTime: '08:00 a.m',
    closingTime: '11:00 p.m',
  },
  {
    id: 6,
    image: lib1,
    title: 'Digital Library',
    city: 'Gorakhpur',
    location: 'Civil Lines, Gorakhpur',
    price: 65,
    latitude: 26.7550,
    longitude: 83.3731,
    totalseats: 10,
    openingTime: '08:00 a.m',
    closingTime: '11:00 p.m',
  },
  {
    id: 7,
    image: lib2,
    title: 'Knowledge Hub',
    city: 'Gorakhpur',
    location: 'Shivpur, Gorakhpur',
    price: 50,
    latitude: 26.7600,
    longitude: 83.3700,
    totalseats: 20,
    openingTime: '08:00 a.m',
    closingTime: '11:00 p.m',
  },
  {
    id: 8,
    image: lib4,
    title: 'Reading Room',
    city: 'Gorakhpur',
    location: 'Mahatma Gandhi Road, Gorakhpur',
    price: 45,
    latitude: 26.7580,
    longitude: 83.3760,
    totalseats: 18,
    openingTime: '08:00 a.m',
    closingTime: '11:00 p.m',
  },
];

export default libraryData;
